[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/api/*"
  to = ":splat"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*", Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, x-auth-token", Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"}

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200